name: "[ci] Lint and compile source code"

on:
  pull_request:
    branches:
      - "*"

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
          cache-prefix: v1
          dune-cache: true

      - name: Generate the output file
        working-directory: ./src
        run: eval $(opam env) && dune exec internships > ../README.md
        
      - name: Commit and push changes to git
        run: |
          git fetch
          git checkout ${{ github.head_ref }}
          git pull
          git add -f README.md

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git commit -m "[bot] auto-update README.md"
            git push origin HEAD:${{ github.head_ref }}
          fi
